branches: default

matrix:
  HERCULES_SERVER_MODE:
    - "classic"
    # - "renewal"
  HERCULES_PACKET_VERSION:
    - "latest"
    # - "20180418"

pipeline:
  docker-build:
    image: thegeeklab/drone-docker-buildx
    secrets:
      - dockerhub_username
      - dockerhub_token
    pull: true
    commands:
      - echo $${DOCKERHUB_TOKEN} | docker login --username $${DOCKERHUB_USERNAME} --password-stdin
      - > 
        docker buildx build
        --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
        --tag florianpiesche/hercules:${HERCULES_SERVER_MODE}-packetver-${HERCULES_PACKET_VERSION}
