branches: default

matrix:
  HERCULES_SERVER_MODE:
    - "classic"
    - "renewal"
  HERCULES_PACKET_VERSION:
    - "latest"
    - "20180418"

pipeline:
  docker-build:
    image: thegeeklab/drone-docker-buildx
    pull: true
    commands:
      - docker login
      - > 
        docker buildx build --push
        --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
        --tag florianpiesche/hercules:${HERCULES_SERVER_MODE}-packetver-${HERCULES_PACKET_VERSION}
