name: Hercules Docker images

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
    paths:
      - '*.sh'
      - 'distrib-tmpl/**'
      - 'Dockerfile'
      - 'hercules/**'
      - '.gitmodules'
  pull_request:
    branches:
      - main
    paths:
      - '*.sh'
      - 'distrib-tmpl/**'
      - 'Dockerfile'
      - 'hercules/**'
      - '.gitmodules'

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' }}
  BUILD_RELEASE: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: Dockerfile

    - name: Lint build shell scripts
      run: shellcheck *.sh

  build-hercules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HERCULES_SERVER_MODE: ["classic", "renewal"]
        HERCULES_PACKET_VERSION: ["20180418", "latest"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Get latest release tag
        run: |
          HERCULES_VERSION=$(basename $(curl -fs -o/dev/null -w %{redirect_url} https://github.com/HerculesWS/Hercules/releases/latest))
          echo "HERCULES_VERSION=${HERCULES_VERSION}" >> $GITHUB_ENV
          cd hercules
          git checkout ${HERCULES_VERSION}

      - name: Get Hercules packet version
        run: |
          if [[ ${{ matrix.HERCULES_PACKET_VERSION }} == "latest" ]]; then
            PACKETVER=$(sed -n -e 's/^.*#define PACKETVER \(.*\)/\1/p' hercules/src/common/mmo.h)
          else
            PACKETVER=${{ matrix.HERCULES_PACKET_VERSION }}
          fi
          echo "HERCULES_PACKETVER=$PACKETVER" >> $GITHUB_ENV

      - name: Check whether latest release needs building
        if: ${{ env.PUSH_IMAGE == 'true' }}
        run: |
          # Check whether there already is a Docker image for the current tag
          SERVER_TAGS=$(curl -s https://registry.hub.docker.com/v1/repositories/${{ secrets.DOCKERHUB_USERNAME }}/hercules-${{ matrix.HERCULES_SERVER_MODE }}-packetver${{ env.HERCULES_PACKETVER }}/tags | jq -r ".[].name") || SERVER_TAGS="none"
          for tag in ${SERVER_TAGS[@]}; do
            if [[ "$tag" == "${HERCULES_VERSION}" ]]; then
              echo "Release ${tag} has already been built."
              echo "BUILD_RELEASE=false" >> $GITHUB_ENV
              exit
            fi
          done

      - name: Set up QEMU for Docker
        if: ${{ env.BUILD_RELEASE == 'true' }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: ${{ env.BUILD_RELEASE == 'true' }}
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and publish images
        if: ${{ env.BUILD_RELEASE == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: ${{ env.PUSH_IMAGE }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hercules-${{ matrix.HERCULES_SERVER_MODE }}-packetver-${{ env.HERCULES_PACKETVER }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hercules-${{ matrix.HERCULES_SERVER_MODE }}-packetver-${{ env.HERCULES_PACKETVER }}:${{ env.HERCULES_VERSION }}
            ghcr.io/${{ github.repository_owner }}/hercules-${{ matrix.HERCULES_SERVER_MODE }}-packetver-${{ env.HERCULES_PACKETVER }}:latest
            ghcr.io/${{ github.repository_owner }}/hercules-${{ matrix.HERCULES_SERVER_MODE }}-packetver-${{ env.HERCULES_PACKETVER }}:${{ env.HERCULES_VERSION }}
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            HERCULES_SERVER_MODE=${{ matrix.HERCULES_SERVER_MODE }}
            HERCULES_PACKET_VERSION=${{ matrix.HERCULES_PACKET_VERSION }}
            HERCULES_RELEASE=${{ env.HERCULES_VERSION }}
